server:
  port: 81

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    suffix: .html
    check-template-location: false
  servlet:
    multipart:
      enabled: true
      location: ${wayn.uploadDir}
      file-size-threshold: 5MB
      max-file-size: 200MB
      max-request-size: 200MB

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# 日志配置
logging:
  level:
    com.wayn: debug
    org.springframework: info
    com.baomidou: info

# mybatis plus 配置
mybatis-plus:
  scripting-language-driver:
    velocity:
      additional-context-attributes:
  global-config:
    db-config:
      logic-delete-field: delFlag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 搜索指定包别名
  typeAliasesPackage: com.wayn.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# wayn配置
wayn:
  name: wayn
  version: 1.1.0
  email: 166738430@qq.com
  uploadDir: E:/wayn/upload

# 七牛云配置
qiniu:
  enabled: true
  ## 此处填写你自己的七牛云 access key
  accessKey: 0m7AYz601l-UiO_9uyK0c8TEJqnbdkAPln7dgjVw
  ## 此处填写你自己的七牛云 secret key
  secretKey: 0Z0caBUehc7uRhiIwcTjfVxR9MoDJDIDtRaaNP3O
  ## 此处填写你自己的七牛云 bucket
  bucket: wayntest
  ## 此处填写你自己的七牛云 域名
  prefix: http://cdn.wayn.xin