version: '3'
services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez
      - ./rabbitmq/plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/lib/rabbitmq
    environment:
      #rabbitmq的初始用户名
      RABBITMQ_DEFAULT_USER: guest
      #rabbitmq的初始密码
      RABBITMQ_DEFAULT_PASS: guest
    network_mode: "host"
  # Elasticsearch服务
  elasticsearch:
    image: elasticsearch:7.14.0
    ports:
      - "9200:9200"
    container_name: elasticsearch
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD="123456"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    network_mode: "host"
