server:
  port: 85
  shutdown: graceful # 优雅关机
spring:
  application:
    name: waynboot-message-consumer
  boot:
    admin:
      client:
        url: http://127.0.0.1:89/boot-admin

# 日志配置
logging:
  level:
    com.wayn: info
    org.springframework: info
  file:
    name: ${LOG_PATH_PREFIX:E:/home}/${spring.application.name}/info.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    logfile:
      external-file: ${logging.file.name}
    health:
      show-details: always
