server:
  port: 85

spring:
  #配置rabbitMq 服务器
  rabbitmq:
    host: 182.254.214.165
    port: 5672
    username: admin
    password: admin

# 日志配置
logging:
  level:
    com.wayn: debug
    org.springframework: info