server:
  port: 85

spring:
  #配置rabbitMq 服务器
  rabbitmq:
    host: wayn.ltd
    port: 5672
    username: guest
    password: guest

# 日志配置
logging:
  level:
    com.wayn: debug
    org.springframework: info
